In [7]:
scores = [78,69,65]
new_score = []

for score in scores:
    new_score.append(score + 3)

print(new_score)


[81, 72, 68]


In [8]:
scores = [78,69,65]
new_score = [score + 3 for score in scores]
print(new_score)


[81, 72, 68]


In [9]:
scores = [78,69,65]
scores * 2 

[78, 69, 65, 78, 69, 65]

In [10]:
[78,69,65] + [78,69,65]


[78, 69, 65, 78, 69, 65]

In [ ]:
import numpy as np

scores = np.array([78,69,65])
print(scores + 3)
scores + 3


[81 72 68]



array([81, 72, 68])

In [13]:
scores.sum()
scores.mean()
scores.std()
scores.var()
scores.min()
scores.max()
np.median(scores)



69.0

In [16]:
students = np.array([[67,94,65], [88,82,78], [90,90,90]])

students



array([[67, 94, 65],
       [88, 82, 78],
       [90, 90, 90]])

In [21]:
students.ndim, students.shape, students.size, students.dtype



(2, (3, 3), 9, dtype('int32'))

In [23]:
# 第一個學生的成績
students[0, :]


array([67, 94, 65])

In [ ]:
# 2學生的成績
students[0:2,:]

array([[67, 94, 65],
       [88, 82, 78]])

In [27]:
students[:,0:2]

array([[67, 94],
       [88, 82],
       [90, 90]])

In [30]:
# first column
students[:,0]

array([67, 88, 90])

In [32]:
# first row data
students[-3]

array([67, 94, 65])

In [37]:
# list 2 column
students[:,:2]

array([[67, 94],
       [88, 82],
       [90, 90]])

In [44]:
students[0,0] = 76
students


array([[76, 94, 65],
       [88, 82, 78],
       [90, 90, 90]])